issues:
  exclude-use-default: false
  exclude:
    - "^don't use ALL_CAPS"
    - "^ST1003: should not use ALL_CAPS"
    - "^G304: Potential file inclusion via variable"

linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - depguard
    - dupword
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - goconst
    - gocyclo
    - godox
    - golint
    - gomnd
    - ifshort
    - interfacer
    - interfacebloat
    - ireturn
    - lll
    - maligned
    - nlreturn
    - nilnil
    - nosnakecase
    - paralleltest
    - revive
    - scopelint
    - structcheck
    - tagalign
    - testpackage
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl
