issues:
  exclude-use-default: false
  exclude:
    - "^don't use ALL_CAPS"
    - "^ST1003: should not use ALL_CAPS"
    - "^var-naming: don't use ALL_CAPS"
    - "^G302: Expect file permissions to be 0600 or less"
    - "^G304: Potential file inclusion via variable"
    - "^G306: Expect WriteFile permissions to be 0600 or less"
    - "^G301: Expect directory permissions to be 0750 or less"

linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - dupword
    - execinquery
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - goconst
    - gocyclo
    - godox
    - gomnd
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - nilnil
    - paralleltest
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
