blank_issues_enabled: true
contact_links:
  - name: Questions
    about: Please use Discord for questions, discussions and feature requests.
    url: https://discord.com/channels/1008553546058313738/1142282364492468254
