name: prod
run-name: Production Deployment

on:
  push:
    branches: [main]

jobs:
  # Ensure a successful deploy to staging before deploying to prod
  deploy-stage:
    uses: ./.github/workflows/stage.yaml
    secrets: inherit
    with:
      channel: live

  release:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./bin/make release
        env:
          GITHUB_APP_ID: ${{ secrets.EVYLANGBOT_GITHUB_APP_ID }}
          GITHUB_APP_PEM: ${{ secrets.EVYLANGBOT_GITHUB_APP_PEM }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: prod
      channel: live
      ref: ${{ github.ref }}

  howl-on-fail:
    runs-on: ubuntu-latest
    needs: [deploy-stage, release, deploy-prod]
    if: always() && contains(join(needs.*.result, ','), 'failure')
    steps:
      - uses: actions/checkout@v4
      - run: ./bin/howl
        env:
          # Notify evy Discord server on channel #evydev
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_TEXT: "@here"
