name: prod
run-name: Production Deployment

on:
  push:
    branches: [main]

jobs:
  # Ensure a successful deploy to staging before deploying to prod
  deploy-stage:
    uses: ./.github/workflows/stage.yaml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./bin/make release
        env:
          GITHUB_APP_ID: ${{ secrets.EVYLANGBOT_GITHUB_APP_ID }}
          GITHUB_APP_PEM: ${{ secrets.EVYLANGBOT_GITHUB_APP_PEM }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: release
    environment: prod
    steps:
      - run: ./bin/make deploy-prod
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVY_LANG }}
      - run: ./bin/make e2e
        env:
          BASEURL: ${{ env.BASEURL_APEX }}

  howl-on-fail:
    runs-on: ubuntu-latest
    needs: [deploy-stage, release, deploy-prod]
    if: failure()
    steps:
      - uses: foxygoat/howl@v1
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_TEXT: <!here|here>
