name: stage
run-name: Staging Deployment

on:
  pull_request:
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
        description: "Firebase deployment channel, live or PRNUM"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./bin/make check-uptodate build-go test
        env:
          TERM: vt100

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./bin/make lint

  deploy:
    if: github.repository_owner == 'evylang'
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: stage
      channel: ${{ inputs.channel || github.event.number }}
      ref: ${{ github.ref }}

  trigger-deploy:
    if: github.event.repository_owner != 'evylang'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: gh workflow run deploy.yaml -r ${{ github.ref }} -f environment=stage -f channel=${{ github.event.number }} -f ref=${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
