name: stage
run-name: Staging Deployment

on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./bin/make build-go test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./bin/make lint

  check-uptodate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./bin/make ci-check-uptodate
        env:
          TERM: vt100

  deploy:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./bin/make deploy ENV=stage CHANNEL= # empty channel becomes PR-NUM or "live"
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVY_LANG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./bin/make e2e USE_DOCKER=1
        env:
          BASEURL: ${{ env.BASEURL_APEX }}
          BASEURL_PLAY: ${{ env.BASEURL_PLAY }}
          BASEURL_DOCS: ${{ env.BASEURL_DOCS }}
