name: stage
run-name: Staging Deployment

on:
  pull_request:
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
        description: "Firebase deployment channel, live or PRNUM"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./bin/make check-uptodate build-go test
        env:
          TERM: vt100

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./bin/make lint

  deploy:
    if: github.repository == 'evylang/evy'
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: stage
      channel: ${{ inputs.channel || github.event.number }}
      ref: ${{ github.ref }}
