name: stage
run-name: Staging Deployment

on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./bin/make check-uptodate
        env:
          TERM: vt100
      - run: ./bin/make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./bin/make lint

  deploy:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./bin/make deploy
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVY_LANG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./bin/make e2e-docker
        env:
          BASEURL: ${{ env.BASEURL_APEX }}
          BASEURL_PLAY: ${{ env.BASEURL_PLAY }}
